language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

addons:
    firefox: latest

before_script:
    - npm install

script:
    - npm test
