language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

addons:
    firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
    - npm install

script:
    - npm start & npm test
